language: android
jdk: oraclejdk8
branches:
  only:
  - test-builds
  - "/^v([0-9]+)\\.([0-9]+).*$/"
android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository
addons:
  apt:
    packages:
    - python3
  ssh_known_hosts: modos189.ru
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: ShFUiDihR1hJY+bMPTzc+0wKE7k3OrTAuUA8TthOLA2gTrzjrwB9tqNdeQeFOifUVCoaFtZQSRWYVE4/Lo76o1yR0j4HuFvA6GfjR9OmJCBtRLmg6sVou9as2oONZsJUhK/fra67hd41/X03TfCgaC0lxghIbaSAfUM1J9nZRjHzpQ83j9a8HUCXVpZ7WJKhmv4Os0CPz6r8pgoIm/sCwyGUyKjWS73bpBQz6ycUyO2Ks5VsKxp2JkMPQkWpK68pRlSUOkN6khkKsa04D+IxeXt829GESnNr7B0HAev+lxiIZYkSFU6B7J3xfb96eEefMSHqKTrSskKwLYGfIMP3uc8zCwn1R3rqaQsKazG7gXmINCkSHMiYrxYHrVj5EhGJ5AYLWWimYAw1O+0VlrQA09Wh8vs+mOFTxsDdUIyL7hAzNHCd1iNtev4GG2Cm4wEeTqP92bVCRWt8LRLEmTuX99k/B9xKQD8mrIksv4fSwQVdwxJeSMAKynM4PtOY+0E1fHlJvqTvqJpYOVdQ2AMSC5gl0Jw44uoybC2ViUGsIwZll8mol1/Atz4On2yyZvd2wUkOrlLXj82P8nIBIdthsXsWPV2NMVqpOTV+4+Lm1rZJhaZglEU4Hgh06VAsoAs7fe05raSTxihOY1QLSMEEF+T5yQTiXfRAwf9969E4kqw=
jobs:
  include:
  - stage: test-builds
    if: branch = test-builds
    env: BUILD_TYPE=test
  - stage: release
    if: branch != test-builds
    env: BUILD_TYPE=release
before_script:
- git fetch --unshallow
- openssl aes-256-cbc -K $encrypted_460819c10bef_key -iv $encrypted_460819c10bef_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- chmod 600 /tmp/deploy_rsa
- eval "$(ssh-agent -s)"
- ssh-add /tmp/deploy_rsa
script:
- wget https://iitc.modos189.ru/deploy/$BUILD_TYPE/localbuildsettings.py
- "./build.py $BUILD_TYPE"
- "./build.py mobile"
deploy:
  provider: releases
  name: "$TRAVIS_TAG"
  skip_cleanup: true
  api_key:
    secure: KoJXTxCoatpFbQgbW1VBIh1ndtQIEmj68sANI+zOs54vi9XMCG3RM4cFn4y7YsSI/kz6XcoSC30SNnqedxHMPJyjrIWvVLKDTlbJswZmGhsslrZmClw3sFROKodVI5DoI0520mAfwzQ5PInPpSEfsPZQhA9ufv1wTZ/98q2efcRPu3J6riSdOZmqJ2A+veWpID3t3P57Lcjew+P3PdmUpwC9t6Yp4oQaYX4DZvMMpqK6s8E4EfOVQptaFAxYDIlAIWxNsfIJkx3jwmLdyaSwQL/fyesQ3fZRECKZTN7RM8/2nImuBZsq4uKS3nrKpLEXFTId45ET5N0fa23KXMLMM8NW0LlATLLWju+N7dP2HCeV5w2wxh+ToAR58XciiZLIsxI1IfF8WXloPax6DmJYksEKOenMYB/y/VASi5xbEhl89kdkxAaO6hAoVqKYo+xt7y3nPGSDUf+zfJnno5lPXgF3ctVAjmRBTWUSQQ5VhAeOp2LGg8ennzSkaLKxqyIxJ7F+n7Y0/QmG0uQzmerOjEEjVBsyVawRWjZGrDlog3Pq2S0n4vnbvbtUchwp/Fapjtg1f1pWy9Bzi1tnnE4ALJEmM894izxWH4vtDQu1+nkjKtLrkxgjk5yEuPj3n95ab64UO1To/x4YlyApmLkDeZIEMd+5siBTeGlB1V05Mr4=
  file_glob: true
  file:
  - "./build/mobile/IITC_Mobile-release.apk"
  - "./build/release/*"
  on:
    repo: IITC-CE/ingress-intel-total-conversion
    tags: true
    all_branches: true
    condition: "$TRAVIS_BRANCH != test-builds"
